In [14]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

np.zeros((2,3))

np.ones((2,3))

np.arange(10)

np.arange(2, 10, dtype=float)

np.arange(2, 3, 0.1)

np.linspace(1., 4., 6)

np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [19]:
# IO with numpy
# genfromtxt

from io import StringIO


data = u"1, 2, 3\n4, 5, 6"
np.genfromtxt(StringIO(data), delimiter=",")

data = u"  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data), delimiter=3)

data = u"123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data), delimiter=(4,3,2))


# autostrip removes trailing whitespaces
data = u"1, abc , 2\n 3, xxx, 4"
np.genfromtxt(StringIO(data), delimiter=",", autostrip=True, dtype="|U5")

# comments arguments
data = u"""#
# Skip me !
# Skip me too !
1, 2
3, 4
5, 6 #This is the third line of the data
7, 8
# And here comes the last line
9, 0
"""

np.genfromtxt(StringIO(data), comments="#", delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

array([['1', 'abc', '2'],
       ['3', 'xxx', '4']], dtype='<U5')

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [29]:
# using a converter func

data = u"1, , 3\n 4, 5, 6"

convert = lambda x: float(x.strip() or -999)

np.genfromtxt(StringIO(data), delimiter=",",
              converters={1: convert})

array([[   1., -999.,    3.],
       [   4.,    5.,    6.]])

In [33]:
# example of using missing_values and filling_values
# In the following example, we suppose that the missing values are 
# flagged with "N/A" in the first column and by "???" in the third column.
# We wish to transform these missing values to 0 if they occur in the 
# first and second column, and to -999 if they occur in the last column:

data = u"N/A, 2, 3\n4, ,???"

kwargs = dict(
    delimiter= ",",
    dtype=int,
    names="a,b,c",
    missing_values={"a":"N/A", "b":" ", "c": "???"},
    filling_values={"a":0, "b": 0, "c": -999}
)

np.genfromtxt(StringIO(data), **kwargs)

array([(0, 2,     3), (4, 0, -9998)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [ ]:
# TODO:
# Indexing