In [20]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from numpy import array

a = array([[1.0, 0.0, 0.0], [1.0, 2.0, 3.0]])

print(a)
print("Dimensions: {}".format(a.ndim))
print("Shape: {}".format(a.shape))
print("Size: {}".format(a.size))
print("Data Type: {}".format(a.dtype))

[[1. 0. 0.]
 [1. 2. 3.]]
Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: float64


In [28]:
# Example 1

import numpy as np

a = np.arange(15).reshape(3,5)
print(a)

print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

type(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15


numpy.ndarray

In [43]:
# Example 2 
# Creating arrays

import numpy as np

a = np.array([1,2,3])
print(a)
print(a.dtype)
print(a.shape)
print(a.ndim)

b = np.array([(1.5, 2.5, 3.5), (4.5, 5.5, 6.5)])
print(b)
print(b.shape)
print(b.ndim) # => axes 2


c = np.array([[1,2], [3,4]], dtype='complex')
print(c)

d = np.zeros((3,4))
print(d)
print(d.shape)
print(d.ndim)

np.ones((2,3,4))

np.empty((2,3))

[1 2 3]
int64
(3,)
1
[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
(2, 3)
2
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
2


array([[1.5, 2.5, 3.5],
       [4.5, 5.5, 6.5]])

In [47]:
# Example 3
# Create seq of numbers

import numpy as np
from numpy import pi

np.arange(10, 30, 5)

# When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

x = np.linspace(0, 2, 9)
print(x)

x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
print(f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.1367739

In [52]:
# Example 4
# Printing arrays

import numpy as np

a = np.arange(6)
print(a)

b = np.arange(12).reshape(4,3)
print(b)

c = np.arange(24).reshape(2,3,4)
print(c)

# If an array is too large to be printed, 
# NumPy automatically skips the central part of the array and only prints the corners:

print(np.arange(1000))


print(np.arange(1000).reshape(10, 100))

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 2

In [6]:
# Example 5
# Basic operations 
# Arithmetic operations apply on arrays elementwise. New array created and filled with the result.

import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
print(c)

print(b ** 2)

print(10*np.sin(a))

print(a<35)


[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [11]:
# Example 6
# Basic Operations
# Product operator * operates elementwise in numpy arrays
# Matrix product performed using @ operator or dot function


A = np.array([
    [1,1],
    [0,1]
])

print(A.shape)

B = np.array([
    [2,0],
    [3,4]
])
print(B.shape)

print(A * B) # elementwise product

print(A @ B) # matrix product

print(A.dot(B)) # matrix product

(2, 2)
(2, 2)
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [17]:
# Example 7
# Basic operations:
# Some operators modify an existing array in place

a = np.ones((2,3), dtype=int)
b= np.random.random((2,3))

a *= 3
print(a)

print(b)

b += a
print(b)

a += b

[[3 3 3]
 [3 3 3]]
[[0.49081958 0.34350565 0.84035582]
 [0.19879838 0.76056264 0.9461995 ]]
[[3.49081958 3.34350565 3.84035582]
 [3.19879838 3.76056264 3.9461995 ]]


TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [26]:
# Example 8
# Upcasting

a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
b
b.dtype.name

c = a + b
c # => a cast from integer to float64
c.dtype.name

d = np.exp(c*1j)
d
d.dtype.name

array([0.        , 1.57079633, 3.14159265])

'float64'

array([1.        , 2.57079633, 4.14159265])

'float64'

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

'complex128'

In [29]:
# Example 9
# Unary operators

a = np.random.random((2,3))
a
a.sum()
a.min()
a.max()

array([[0.02842866, 0.0304754 , 0.51691545],
       [0.4402301 , 0.77296883, 0.93335807]])

2.7223765159227917

0.028428657153907744

0.9333580664991558

In [33]:
# Example 10
# Above operations apply to array as if it was a list of numbers, regardless of shape
# Specify axis parameter to apply operation along specified axis of array

b = np.arange(12).reshape(3,4)
b

b.sum(axis=0) # sum of each column

b.min(axis=1) # min of each row

b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([12, 15, 18, 21])

array([0, 4, 8])

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [38]:
# Example 11
# Unary operations

B = np.arange(3)
B

np.exp(B)

np.sqrt(B)

C = np.array([2, -1, 4])
np.add(B, C)

array([0, 1, 2])

array([1.        , 2.71828183, 7.3890561 ])

array([0.        , 1.        , 1.41421356])

array([2, 0, 6])

array([0, 1, 2])

In [48]:
# Example 12
# Iteration

a = np.arange(10) ** 3
a

a[2]
a[2:5]

a[:6]
a[:6:2]

a[:6:2] -= 1000
a

a[ : :-1]

for i in a:
    print(i ** (1/3.))

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

8

array([ 8, 27, 64])

array([  0,   1,   8,  27,  64, 125])

array([ 0,  8, 64])

array([-1000,     1,  -992,    27,  -936,   125,   216,   343,   512,
         729])

array([  729,   512,   343,   216,   125,  -936,    27,  -992,     1,
       -1000])

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/Users/chee/numpy_tutorial_2019/venv/lib/python3.6/site-packages/ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in power


In [57]:
def f(x,y):
    return 10 * x + y

b = np.fromfunction(f, (5,4), dtype=int)
b

b[2,3]

b[0:5, 1]
b[:, 1]

b[1:3, :]

for e in b.flat:
    print(e)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

23

array([ 1, 11, 21, 31, 41])

array([ 1, 11, 21, 31, 41])

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
