In [8]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

np.zeros((2,3))

np.ones((2,3))

np.arange(10)

np.arange(2, 10, dtype=float)

np.arange(2, 3, 0.1)

np.linspace(1., 4., 6)

np.indices((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([2., 3., 4., 5., 6., 7., 8., 9.])

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
# TODO:

# IO with numpy
# Indexing
# Broadcasting
# Byte-swapping
# Structured Arrays
# Subclassing ndarray